# Generated by Django 6.1 on 2026-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='method',
            field=models.CharField(blank=True, choices=[('', 'Sem método'), ('ppl', 'Push Pull Legs'), ('upper_lower', 'Upper Lower'), ('full_body', 'Full Body'), ('abc', 'ABC'), ('other', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='modality',
            field=models.CharField(choices=[('strength', 'Musculação'), ('martial', 'Artes marciais'), ('cardio', 'Cardio'), ('other', 'Outro')], default='strength', max_length=20),
        ),
    ]
