# Generated by Django 6.1 on 2026-08-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
