# Generated by Django 6.1 on 2026-08-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_book_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
