# Generated by Django 6.1 on 2026-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('binary', 'Sim/Não'), ('quantity', 'Quantidade'), ('duration', 'Duração')], default='binary', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='target',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
